version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./deployment/Dockerfile
      target: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: ./deployment/Dockerfile
      target: frontend
    ports:
      - "3000:80"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
