name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r backend/requirements.txt

    - name: Run backend tests
      run: |
        cd backend && python manage.py test

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install frontend dependencies
      run: |
        cd frontend && npm install

    - name: Run frontend tests
      run: |
        cd frontend && npm test

    - name: Build Docker images
      run: |
        docker build -t my-backend-image:latest --target=backend .
        docker build -t my-frontend-image:latest --target=frontend .

    - name: Push to DockerHub
      run: |
        echo "${{ secrets.DOCKERHUB_USERNAME }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        docker push my-backend-image:latest
        docker push my-frontend-image:latest
